In [1]:
import numpy as np
import numpy.linalg as la

T = np.array([[1,0],[2,-1]])
C = np.array([[1,0],[1,1]])
NT = la.inv(C)@T@C
NT

array([[ 1.,  0.],
       [ 0., -1.]])

In [2]:
a = np.array([[1,0],[1,1]])
d = np.array([[1,0],[0,-1]])
d3 = d*d*d*d*d
a1= la.inv(a)
a @ d3 @ a1
a.shape

(2, 2)

In [1]:
# Before we begin, let's load the libraries.
%pylab notebook
import numpy as np
import numpy.linalg as la
from readonly.PageRankFunctions import *
np.set_printoptions(suppress=True)

Populating the interactive namespace from numpy and matplotlib


ModuleNotFoundError: No module named 'readonly'

In [2]:
# Replace the ??? here with the probability of clicking a link to each website when leaving Website F (FaceSpace).
L = np.array([[0,   1/2, 1/3, 0, 0,   0 ],
              [1/3, 0,   0,   0, 1/2, 0 ],
              [1/3, 1/2, 0,   1, 0,   0.5 ],
              [1/3, 0,   1/3, 0, 1/2, 0.5 ],
              [0,   0,   0,   0, 0,   0 ],
              [0,   0,   1/3, 0, 0,   0 ]])

In [3]:
r = 100 * np.ones(6) / 6 # Sets up this vector (6 entries of 1/6 × 100 each)
r # Shows it's value

array([ 16.66666667,  16.66666667,  16.66666667,  16.66666667,
        16.66666667,  16.66666667])

In [5]:
r = L @ r # Apply matrix L to r
r # Show it's value
# Re-run this cell multiple times to converge to the correct answer.

array([ 19.90740741,   4.62962963,  42.12962963,  20.37037037,
         0.        ,  12.96296296])

In [6]:
# PACKAGE
# Here are the imports again, just in case you need them.
# There is no need to edit or submit this cell.
import numpy as np
import numpy.linalg as la
from readonly.PageRankFunctions import *
np.set_printoptions(suppress=True)

ModuleNotFoundError: No module named 'readonly'

In [7]:
# GRADED FUNCTION
# Complete this function to provide the PageRank for an arbitrarily sized internet.
# I.e. the principal eigenvector of the damped system, using the power iteration method.
# (Normalisation doesn't matter here)
# The functions inputs are the linkMatrix, and d the damping parameter - as defined in this worksheet.
def pageRank(linkMatrix, d) :
    n = linkMatrix.shape[0]
    M = d * linkMatrix + (1-d)/n * np.ones([n, n]) # np.ones() is the J matrix, with ones for each entry.
    r = 100 * np.ones(n) / n # Sets up this vector (6 entries of 1/6 × 100 each)
    lastR = r
    r = M @ r
    i = 0
    while la.norm(lastR - r) > 0.01 :
        lastR = r
        r = M @ r
        i += 1
    r
    return r


In [8]:
# Do note, this is calculating the eigenvalues of the link matrix, L,
# without any damping. It may give different results that your pageRank function.
# If you wish, you could modify this cell to include damping.
# (There is no credit for this though)

eVals, eVecs = la.eig(L) # Gets the eigenvalues and vectors
order = np.absolute(eVals).argsort()[::-1] # Orders them by their eigenvalues
eVals = eVals[order]
eVecs = eVecs[:,order]

r = eVecs[:, 0]
100 * np.real(r / np.sum(r))

array([ 16.        ,   5.33333333,  40.        ,  25.33333333,
         0.        ,  13.33333333])

In [9]:
%%timeit
eVals, eVecs = la.eig(L) # Gets the eigenvalues and vectors
order = np.absolute(eVals).argsort()[::-1] # Orders them by their eigenvalues
eVals = eVals[order]
eVecs = eVecs[:,order]

r = eVecs[:, 0]
100 * np.real(r / np.sum(r))

The slowest run took 6.58 times longer than the fastest. This could mean that an intermediate result is being cached.
300 µs ± 215 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
# You may wish to view the PageRank graphically.
# This code will draw a bar chart, for each (numbered) website on the generated internet,
# The height of each bar will be the score in the PageRank.
# Run this code to see the PageRank for each internet you generate.
# Hopefully you should see what you might expect
# - there are a few clusters of important websites, but most on the internet are rubbish!
%pylab notebook
r = pageRank(generate_internet(100), 0.9)
plt.bar(arange(r.shape[0]), r);

In [12]:
import numpy as np
M = np.array([[4,-5,6],
              [7,-8,6],
             [3/2,-1/2,-2]])
vals, vecs = np.linalg.eig(M)
print(vals)
print(vecs)

[ 1. -4. -3.]
[[-0.6882472  -0.66666667  0.40824829]
 [-0.6882472  -0.66666667 -0.40824829]
 [-0.22941573  0.33333333 -0.81649658]]


In [14]:
import numpy as np
M = np.array([[0,1,0,0],
              [1,0,0,0],
            [0,0,0,1],
             [0,0,1,0]])
vals, vecs = np.linalg.eig(M)
print(vals)
print(vecs)
np.linalg.det(M)

[ 1. -1.  1. -1.]
[[ 0.70710678 -0.70710678  0.          0.        ]
 [ 0.70710678  0.70710678  0.          0.        ]
 [ 0.          0.          0.70710678 -0.70710678]
 [ 0.          0.          0.70710678  0.70710678]]


1.0

In [15]:
import numpy as np
M = np.array([[.1,.7,0.1,0.1],
              [.7,0.1,0.1,0.1],
            [0.1,0.1,0.1,.7],
             [0.1,0.1,.7,0.1]])
vals, vecs = np.linalg.eig(M)
print(vals)
print(vecs)
np.linalg.det(M)

[-0.6  0.6  1.  -0.6]
[[  7.07106781e-01  -5.00000000e-01  -5.00000000e-01  -7.70128341e-02]
 [ -7.07106781e-01  -5.00000000e-01  -5.00000000e-01   7.70128341e-02]
 [ -1.09175934e-18   5.00000000e-01  -5.00000000e-01  -7.02900436e-01]
 [  1.10513050e-17   5.00000000e-01  -5.00000000e-01   7.02900436e-01]]


0.21600000000000003